### ISSUE TITLE
Short names and versions

### ISSUE THREAD

**Issue by Memnarch** [lynatan/Restore-Form-Designer-Option-for-Starter-Edition#1]
Hi,
Thanks for Contributing to the Delphinus packagemanager. Already tried them out :).

Just 2 little suggestions to improve them:
1. Add a release on Github for each package( with a version like 1 or 1.0.0). This allows Delphinus to Display Updates when you update one of your packages. Otherwhise users will not notice
2. Use shorter names. Currently your names are quite long. Delphinus extracts the "Description"-Property of a github repo. By using simpler/short names it is easier to use them with the upcoming Commandlinetool.

Sorry for creating this "collection"-issue. Could not find an EMail address to contact you directly.

Greetings
Memnarch

**Comment by superswanman** [comment]
@Memnarch Thanks for your suggestions. I did it ;)
